config/routes.rb
Rails.application.routes.draw do

  resources :competitions do
    resources :comments, module: :competitions
  end
  resources :volunteers do
    resources :comments, module: :volunteers
  end
  resources :internships do
    resources :comments, module: :internships
  end
  resources :jobs do
    resources :comments, module: :jobs
  end
  devise_for :users

  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/contact'

  authenticated :user do
    root :to => 'welcome#index', as: :authenticated_root
  end
  root :to => 'welcome#index'

end

app/models/competition.rb
class Competition < ActiveRecord::Base
	belongs_to :user
	has_many :comments, as: :commentable
end

app/controllers/competitions/comments_controller.rb
class Competitions::CommentsController < CommentsController
	before_action :set_commentable

	private

	def set_commentable
		@commentable = Competition.find(params[:competition_id])
	end
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :set_competition, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index]
  before_filter :require_permission, only: [:edit, :destroy, :update]
  before_filter :must_be_company, only: [:new, :create]

  def must_be_company
    unless current_user && current_user.company?
      redirect_to root_path, notice: "Must be a company to create posts"
    end
  end

  def require_permission
    unless current_user == Competition.find(params[:id]).user || current_user.admin?
      redirect_to root_path, notice: "This post is not owned by your account"
    end
  end
  # GET /competitions
  # GET /competitions.json
  def index
    @competitions = Competition.all
  end

  # GET /competitions/1
  # GET /competitions/1.json
  def show
  end

  # GET /competitions/new
  def new
    @competition = Competition.new
  end

  # GET /competitions/1/edit
  def edit
  end

  # POST /competitions
  # POST /competitions.json
  def create
    @competition = Competition.new(competition_params)
    @competition.user = current_user
    if current_user.admin?
      @competition.confirmed = true
    else
      @competition.confirmed = false
    end
    respond_to do |format|
      if @competition.save
        format.html { redirect_to @competition, notice: 'Competition was successfully created. Waiting for admin to confirm.' }
        format.json { render :show, status: :created, location: @competition }
      else
        format.html { render :new }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /competitions/1
  # PATCH/PUT /competitions/1.json
  def update
    respond_to do |format|
      if @competition.update(competition_params)
        format.html { redirect_to @competition, notice: 'Competition was successfully updated.' }
        format.json { render :show, status: :ok, location: @competition }
      else
        format.html { render :edit }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1
  # DELETE /competitions/1.json
  def destroy
    @competition.destroy
    respond_to do |format|
      format.html { redirect_to competitions_url, notice: 'Competition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_competition
      @competition = Competition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def competition_params
      params.require(:competition).permit(:title, :type, :company_name, :closing_date, :starting_date, :description_text, :location, :confirmed)
    end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_form.html.erb
<%= form_for(@competition) do |f| %>
<% if @competition.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

  <ul>
    <% @competition.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<style type="text/css">
  .col-md-8{
    position: relative;
    min-height: 1px;
    padding-right: 0px;
    padding-left: 0px;
    font-size: 20px;
  }
  .jobs-div{
    margin-bottom: 20px;
    background-color: #fff;
    border: 0.5px;
    padding-left: 0px;
  }
  .input-form-box{
    background-color: #f5f5f5;
    padding-left: 70px;
    padding-bottom: 15px;
  }
  .field{
    padding-top:15px;
  }
  .text-input{
    width:80%;
    height: 36px;
  }
  .selct-input{
    height: 36px;
    width: 10%;
  }
</style>
<div class= "container">
  <div class="col-md-8 col-md-offset-2">
    <div class="jobs-div">
      <div class="input-form-box">
        <div class="field">
          <%= f.label :title %><br>
          <%= f.text_field :title, :class => 'text-input',:placeholder => 'Title' %>
        </div>
        <div class="field">
          <%= f.label :type_of_opportunity %><br>
          <%= f.text_field :type_of_opportunity , :class => 'text-input', :placeholder => 'Type of Opportunity' %>
        </div>
        <div class="field">
          <%= f.label :company_name %><br>
          <%= f.text_field :company_name, :class => 'text-input', :placeholder => 'Company Name'  %>
        </div>
        <div class="field">
          <%= f.label :location %><br>
          <%= f.text_field :location, :class => 'text-input', :placeholder => 'Location'  %>
        </div>
        <div class="field">
          <%= f.label :closing_date %><br>
          <%= f.datetime_select :closing_date, :class => 'select-input' %>
        </div>
        <div class="field">
          <%= f.label :starting_date %><br>
          <%= f.datetime_select :starting_date, :class => 'select-input' %>
        </div>
        <div class="field">
          <%= f.label :description_text %><br>
          <%= f.text_area :description_text , :class => 'text-input', :placeholder => 'Description Text' %>
        </div>
        <!--<div class="field">
          <%= f.label :confirmed %><br>
          <%= f.check_box :confirmed %>
        </div>-->
      </div>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
</div>
<% end %>

app/views/competitions/edit.html.erb
<h1>Editing Competition</h1>

<%= render 'form' %>

<%= link_to 'Show', @competition %> |
<%= link_to 'Back', competitions_path %>

app/views/competitions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Competitions</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <!--
      <th>Type</th>
    -->
      <th>Company name</th>
      <th>Closing date</th>
      <!--
      <th>Starting date</th>
    -->
      <th>Description text</th>
      <th>Location</th>
      <!--
      <th>Confirmed</th>
    -->
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @competitions.each do |competition| %>
      <tr>
        <td><%= competition.title %></td>
        <!--
        <td><%= competition.type_of_opportunity %></td>
      -->
        <td><%= competition.company_name %></td>
        <td><%= competition.closing_date %></td>
        <!--
        <td><%= competition.starting_date %></td>
      -->
        <td><%= competition.description_text %></td>
        <td><%= competition.location %></td>
        <!--
        <td><%= competition.confirmed %></td>
      -->
        <td><%= link_to 'Show', competition %></td>
        <!--
        <td><%= link_to 'Edit', edit_competition_path(competition) %></td>
        <td><%= link_to 'Destroy', competition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Competition', new_competition_path %>

app/views/competitions/new.html.erb
<h1>New Competition</h1>

<%= render 'form' %>

<%= link_to 'Back', competitions_path %>

app/views/competitions/show.html.erb
<style type="text/css">
.container{
  font-size: 16px;
}
.date-adjust{
  position: relative;
  left: 90px;
}
.col-md-10{
  padding-top: 30px;
  font-size: 18px;
  /*border-style:groove ;
  border-width: 1px;*/
}
</style>

<p id="notice"><%= notice %></p>
<div class="container">
  <div class="col-md-10 col-md-offset-1">
    <table border="0" class="table table-striped table-hover ">
    <col width = "190">
      <thead>
      
        <tr>
          <th><strong>Title:</strong></th>
          <th  id='main-table' ><%= @competition.title %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><strong>Type:</strong></td>
          <td><%= @competition.type_of_opportunity %></td>
        </tr>
      </tbody>
      <thead>
        <tr>
          <th><strong>Company name:</strong></th>
          <th  id='main-table' ><%= @competition.company_name %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><strong>Description text:</strong></td>
          <td><%= @competition.description_text %></td>
        </tr>
      </tbody> 
      <thead>
        <tr>
          <th><strong>Location:</strong></th>
          <th><%= @competition.location %></th>
        </tr>
      </thead>
      <thead>
        <tr>
          <th><strong>Confirmed:</strong></th>
          <th><%= @competition.confirmed %></th>
        </tr>
      </thead>       
    </table>
    <table border="0" class="table table-striped table-hover ">
      <thead>
        <tr>
          <td><strong>Dates:</strong></td>
          <td class= "date-adjust"><%= @competition.starting_date %> <strong> &nbsp; &nbsp; &nbsp; &nbsp; To </strong></td>
          <td><%= @competition.closing_date %></td>
        </tr>
      </thead>
    </table>
  </div>
</div>
<% if current_user == @competition.user %>
  <h3>Applications: </h3>
  <% @competition.comments.each do |comment| %>
    <div class="well">
      <%= comment.body %> <br>
    </div>

  <% end %>
<% end %>

<h3>New Application:</h3>
<%= form_for [@competition, Comment.new] do |f| %>
  <div class="form-group">
    <%= f.text_area :body, class: "form-control", placeholder: "Add an application" %>
  </div>
  <%= f.submit  class: "btn btn-primary", value: "Submit Application" %>
<% end %>

<%= link_to 'Edit', edit_competition_path(@competition) %> |
<%= link_to 'Back', competitions_path %>