config/routes.rb
Rails.application.routes.draw do

  resources :competitions do
    resources :comments, module: :competitions
  end
  resources :volunteers do
    resources :comments, module: :volunteers
  end
  resources :internships do
    resources :comments, module: :internships
  end
  resources :jobs do
    resources :comments, module: :jobs
  end
  devise_for :users

  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/contact'

  authenticated :user do
    root :to => 'welcome#index', as: :authenticated_root
  end
  root :to => 'welcome#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :user
	has_many :comments, as: :commentable
end

app/controllers/jobs/comments_controller.rb
class Jobs::CommentsController < CommentsController
	before_action :set_commentable

	private

	def set_commentable
		@commentable = Job.find(params[:job_id])
	end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index]
  before_filter :require_permission, only: [:edit, :destroy, :update]
  before_filter :must_be_company, only: [:new, :create]

  def must_be_company
    unless current_user && current_user.company?
      redirect_to root_path, notice: "Must be a company to create posts"
    end
  end

  def require_permission
    unless current_user == Job.find(params[:id]).user || current_user.admin?
      redirect_to root_path, notice: "This post is not owned by your account"
    end
  end

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    @job.user = current_user
    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :type, :company_name, :closing_date, :starting_date, :description_text, :location, :confirmed, :fulltime, :paid, :salary)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
<% if @job.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

  <ul>
    <% @job.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<style type="text/css">
  .col-md-8{
    position: relative;
    min-height: 1px;
    padding-right: 0px;
    padding-left: 0px;
    font-size: 20px;
  }
  .jobs-div{
    margin-bottom: 20px;
    background-color: #fff;
    border: 0.5px;
    padding-left: 0px;
  }
  .input-form-box{
    background-color: #f5f5f5;
    padding-left: 70px;
  }
  .field{
    padding-top:15px;
  }
  #table{
    padding-top: 15px;
    border: none;
  }
  .text-input{
    width:80%;
    height: 36px;
  }
  .selct-input{
    height: 36px;
    width: 10%;
  }
</style>
<div class= "container">
  <div class="col-md-8 col-md-offset-2">
    <div class="jobs-div">
      <div class="input-form-box">
        <div class="field">
          <%= f.label :title %><br>
          <%= f.text_field :title, :class => 'text-input',:placeholder => 'Title' %>
        </div>
        <div class="field">
          <%= f.label :type_of_opportunity %><br>
          <%= f.text_field :type_of_opportunity , :class => 'text-input', :placeholder => 'Type of Opportunity' %>
        </div>
        <div class="field">
          <%= f.label :company_name %><br>
          <%= f.text_field :company_name, :class => 'text-input', :placeholder => 'Company Name'  %>
        </div>
        <div class="field">
          <%= f.label :location %><br>
          <%= f.text_field :location, :class => 'text-input', :placeholder => 'Location'  %>
        </div>
        <div class="field">
          <%= f.label :closing_date %><br>
          <%= f.datetime_select :closing_date, :class => 'select-input' %>
        </div>
        <div class="field">
          <%= f.label :starting_date %><br>
          <%= f.datetime_select :starting_date, :class => 'select-input' %>
        </div>
        <div class="field">
          <%= f.label :description_text %><br>
          <%= f.text_area :description_text , :class => 'text-input', :placeholder => 'Description Text' %>
        </div>
        <div class="field">
          <%= f.label :salary %><br>
          <%= f.text_field :salary %>
        </div>
        <table class= "table" style="width: 65%">
          <td><%= f.label :fulltime %><br><%= f.check_box :fulltime %></td>
          <td><%= f.label :paid %><br><%= f.check_box :paid %></td>
        </table>
        <!--<div class="field">
          <%= f.label :confirmed %><br>
          <%= f.check_box :confirmed %>
        </div>-->
      </div>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
</div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Jobs</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <!--
      <th>Type Of Opportunity</
      <!--
      <th>Starting date</th>
      -->
      <th>Company name</th>
      <th>Closing date</th>
      <th>Description</th>
      <th>Location</th>
      <!--
      <th>Confirmed</th>
      <th>Fulltime</th>
      <th>Paid</th>
      <th>Salary</th>
      -->
      
      <th colspan="1"></th>
      
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <!--
        <td><%= job.type_of_opportunity %></td>
        -->
        <td><%= job.company_name %></td>
        <td><%= job.closing_date %></td>
        <!--
        <td><%= job.starting_date %></td>
        -->
        <td><%= job.description_text %></td>
        <td><%= job.location %></td>
        <!--
        <td><%= job.confirmed %></td>
        <td><%= job.fulltime %></td>
        <td><%= job.paid %></td>
        <td><%= job.salary %></td>
        -->
        <td><%= link_to 'Show', job %></td>
        <!--
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
      -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<!--Can someone look at this, my text align isnt working and I can find out why. May have something to do with the called create Aplication-->
<style type="text/css">
.container{
  font-size:16px;
  text-align: left;
}
.date-adjust{
  position: relative;
  left: 90px;
}
.col-md-10{
  padding-top: 30px;
  text-align: left;
  font-size: 18px;
  /*border-style:groove ;
  border-width: 1px;*/
}
</style>

<p id="notice"><%= notice %></p>
<div class="container">
  <div class="col-md-10 col-md-offset-1">
    <table border="0" class="table table-striped table-hover ">
      <thead>
        <tr>
          <th><strong>Title:</strong></th>
          <th><%= @job.title %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><strong>Type:</strong></td>
          <td><%= @job.type_of_opportunity %></td>
        </tr>
      </tbody>
      <thead>
        <tr>
          <th><strong>Company name:</strong></th>
          <th><%= @job.company_name %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><strong>Description text:</strong></td>
          <td><%= @job.description_text %></td>
        </tr>
      </tbody> 
      <thead>
        <tr>
          <th><strong>Location:</strong></th>
          <th><%= @job.location %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><strong>Paid:</strong></td>
          <td><%= @job.paid %></td>
        </tr>
      </tbody> 
      <thead>
        <tr>
          <th><strong>Fulltime:</strong></th>
          <th><%= @job.fulltime %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><strong>Salary:</strong></td>
          <td><%= @job.salary %></td>
        </tr>
      </tbody> 
      <thead>
        <tr>
          <th><strong>Confirmed:</strong></th>
          <th><%= @job.confirmed %></th>
        </tr>
      </thead>       
    </table>
    <table border="0" class="table table-striped table-hover ">
      <thead>
        <tr>
          <td><strong>Dates:</strong></td>
          <td class= "date-adjust"><%= @job.starting_date %> <strong> &nbsp; &nbsp; &nbsp; &nbsp; To </strong></td>
          <td><%= @job.closing_date %></td>
        </tr>
      </thead>
    </table>
  </div>
</div>

<% if current_user == @job.user %>
<h3>Applications: </h3>
<% @job.comments.each do |comment| %>
<div class="well">
  <%= comment.body %> <br>
</div>

<% end %>
<% end %>

<h3>New Application:</h3>
<%= form_for [@job, Comment.new] do |f| %>
<div class="form-group">
  <%= f.text_area :body, class: "form-control", placeholder: "Add an application" %>
</div>
<%= f.submit  class: "btn btn-primary", value: "Submit Application" %>
<% end %>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Destroy', @job, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', jobs_path %>