config/routes.rb
Rails.application.routes.draw do

  resources :competitions do
    resources :comments, module: :competitions
  end
  resources :volunteers do
    resources :comments, module: :volunteers
  end
  resources :internships do
    resources :comments, module: :internships
  end
  resources :jobs do
    resources :comments, module: :jobs
  end
  devise_for :users

  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/contact'

  authenticated :user do
    root :to => 'welcome#index', as: :authenticated_root
  end
  root :to => 'welcome#index'

end

app/models/internship.rb
class Internship < ActiveRecord::Base
	belongs_to :user
	has_many :comments, as: :commentable
end

app/controllers/internships/comments_controller.rb
class Internships::CommentsController < CommentsController
	before_action :set_commentable

	private

	def set_commentable
		@commentable = Internship.find(params[:internship_id])
	end
end

app/controllers/internships_controller.rb
class InternshipsController < ApplicationController
  before_action :set_internship, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index]
  before_filter :require_permission, only: [:edit, :destroy, :update]
  before_filter :must_be_company, only: [:new, :create]

  def must_be_company
    unless current_user && current_user.company?
      redirect_to root_path, notice: "Must be a company to create posts"
    end
  end

  def require_permission
    unless current_user == Internship.find(params[:id]).user || current_user.admin?
      redirect_to root_path, notice: "This post is not owned by your account"
    end
  end
  
  # GET /internships
  # GET /internships.json
  def index
    @internships = Internship.all
  end

  # GET /internships/1
  # GET /internships/1.json
  def show
  end

  # GET /internships/new
  def new
    @internship = Internship.new
  end

  # GET /internships/1/edit
  def edit
  end

  # POST /internships
  # POST /internships.json
  def create
    @internship = Internship.new(internship_params)
    @internship.user = current_user
    respond_to do |format|
      if @internship.save
        format.html { redirect_to @internship, notice: 'Internship was successfully created.' }
        format.json { render :show, status: :created, location: @internship }
      else
        format.html { render :new }
        format.json { render json: @internship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /internships/1
  # PATCH/PUT /internships/1.json
  def update
    respond_to do |format|
      if @internship.update(internship_params)
        format.html { redirect_to @internship, notice: 'Internship was successfully updated.' }
        format.json { render :show, status: :ok, location: @internship }
      else
        format.html { render :edit }
        format.json { render json: @internship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /internships/1
  # DELETE /internships/1.json
  def destroy
    @internship.destroy
    respond_to do |format|
      format.html { redirect_to internships_url, notice: 'Internship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_internship
      @internship = Internship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def internship_params
      params.require(:internship).permit(:title, :type, :company_name, :closing_date, :starting_date, :description_text, :location, :confirmed, :fulltime, :paid, :salary)
    end
end

app/helpers/internships_helper.rb
module InternshipsHelper
end

app/views/internships/_form.html.erb
<%= form_for(@internship) do |f| %>
<% if @internship.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@internship.errors.count, "error") %> prohibited this internship from being saved:</h2>

	<ul>
		<% @internship.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>
<style type="text/css">
  .col-md-8{
    position: relative;
    min-height: 1px;
    padding-right: 0px;
    padding-left: 0px;
    font-size: 20px;
  }
  .jobs-div{
    margin-bottom: 20px;
    background-color: #fff;
    border: 0.5px;
    padding-left: 0px;
  }
  .input-form-box{
    background-color: #f5f5f5;
    padding-left: 70px;
  }
  .field{
    padding-top:15px;
  }
  #table{
    padding-top: 15px;
    border: none;
  }
  .text-input{
    width:80%;
    height: 36px;
  }
  .selct-input{
    height: 36px;
    width: 10%;
  }
</style>
<div class= "container">
  <div class="col-md-8 col-md-offset-2">
    <div class="jobs-div">
      <div class="input-form-box">
        <div class="field">
          <%= f.label :title %><br>
          <%= f.text_field :title, :class => 'text-input',:placeholder => 'Title' %>
        </div>
        <div class="field">
          <%= f.label :type_of_opportunity %><br>
          <%= f.text_field :type_of_opportunity , :class => 'text-input', :placeholder => 'Type of Opportunity' %>
        </div>
        <div class="field">
          <%= f.label :company_name %><br>
          <%= f.text_field :company_name, :class => 'text-input', :placeholder => 'Company Name'  %>
        </div>
        <div class="field">
          <%= f.label :location %><br>
          <%= f.text_field :location, :class => 'text-input', :placeholder => 'Location'  %>
        </div>
        <div class="field">
          <%= f.label :closing_date %><br>
          <%= f.datetime_select :closing_date, :class => 'select-input' %>
        </div>
        <div class="field">
          <%= f.label :starting_date %><br>
          <%= f.datetime_select :starting_date, :class => 'select-input' %>
        </div>
        <div class="field">
          <%= f.label :description_text %><br>
          <%= f.text_area :description_text , :class => 'text-input', :placeholder => 'Description Text' %>
        </div>
        <div class="field">
          <%= f.label :salary %><br>
          <%= f.text_field :salary %>
        </div>
        <table class= "table" style="width: 65%">
          <td><%= f.label :fulltime %><br><%= f.check_box :fulltime %></td>
          <td><%= f.label :paid %><br><%= f.check_box :paid %></td>
        </table>
        <!--<div class="field">
          <%= f.label :confirmed %><br>
          <%= f.check_box :confirmed %>
        </div>-->
      </div>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
</div>
<% end %>

app/views/internships/edit.html.erb
<h1>Editing Internship</h1>

<%= render 'form' %>

<%= link_to 'Show', @internship %> |
<%= link_to 'Back', internships_path %>

app/views/internships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Internships</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <!--
      <th>Type Of Opportunity</th>
    -->
      <th>Company name</th>
      <th>Closing date</th>
      <!--
      <th>Starting date</th>
    -->
      <th>Description text</th>
      <th>Location</th>
      <!--
      <th>Confirmed</th>
      <th>Fulltime</th>
      <th>Paid</th>
      <th>Salary</th>
    -->
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @internships.each do |internship| %>
      <tr>
        <td><%= internship.title %></td>
        <!--
        <td><%= internship.type_of_opportunity %></td>
      -->
        <td><%= internship.company_name %></td>
        <td><%= internship.closing_date %></td>
        <!--
        <td><%= internship.starting_date %></td>
      -->
        <td><%= internship.description_text %></td>
        <td><%= internship.location %></td>
        <!--
        <td><%= internship.confirmed %></td>
        <td><%= internship.fulltime %></td>
        <td><%= internship.paid %></td>
        <td><%= internship.salary %></td>
      -->
        <td><%= link_to 'Show', internship %></td>
        <!--
        <td><%= link_to 'Edit', edit_internship_path(internship) %></td>
        <td><%= link_to 'Destroy', internship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Internship', new_internship_path %>

app/views/internships/new.html.erb
<h1>New Internship</h1>

<%= render 'form' %>

<%= link_to 'Back', internships_path %>

app/views/internships/show.html.erb
<style type="text/css">
  .container{
    font-size: 16px;
  }
  .date-adjust{
    position: relative;
    left: 90px;
  }
  .col-md-10{
    padding-top: 30px;
    font-size: 18px;
  /*border-style:groove ;
  border-width: 1px;*/
}
</style>

<p id="notice"><%= notice %></p>
<div class="container">
  <div class="col-md-10 col-md-offset-1">
    <table border="0" class="table table-striped table-hover ">      
      <col width = "190">

      <thead>
        <tr>
          <th><strong>Title:</strong></th>
          <th><%= @internship.title %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><strong>Type:</strong></td>
          <td><%= @internship.type_of_opportunity %></td>
        </tr>
      </tbody>
      <thead>
        <tr>
          <th><strong>Company name:</strong></th>
          <th><%= @internship.company_name %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><strong>Description text:</strong></td>
          <td><%= @internship.description_text %></td>
        </tr>
      </tbody> 
      <thead>
        <tr>
          <th><strong>Location:</strong></th>
          <th><%= @internship.location %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><strong>Paid:</strong></td>
          <td><%= @internship.paid %></td>
        </tr>
      </tbody> 
      <thead>
        <tr>
          <th><strong>Fulltime:</strong></th>
          <th><%= @internship.fulltime %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><strong>Salary:</strong></td>
          <td><%= @internship.salary %></td>
        </tr>
      </tbody> 
      <thead>
        <tr>
          <th><strong>Confirmed:</strong></th>
          <th><%= @internship.confirmed %></th>
        </tr>
      </thead>       
    </table>
    <table border="0" class="table table-striped table-hover ">
      <thead>
        <tr>
          <td><strong>Dates:</strong></td>
          <td class= "date-adjust"><%= @internship.starting_date %> <strong> &nbsp; &nbsp; &nbsp; &nbsp; To </strong></td>
          <td><%= @internship.closing_date %></td>
        </tr>
      </thead>
    </table>
  </div>
</div>
<% if current_user == @internship.user %>
<h3>Applications: </h3>
<% @internship.comments.each do |comment| %>
<div class="well">
  <%= comment.body %> <br>
</div>
<% end %>
<% end %>

<h3>New Application:</h3>
<%= form_for [@internship, Comment.new] do |f| %>
<div class="form-group">
  <%= f.text_area :body, class: "form-control", placeholder: "Add an application" %>
</div>
<%= f.submit  class: "btn btn-primary", value: "Submit Application" %>
<% end %>

<%= link_to 'Edit', edit_internship_path(@internship) %> |
<%= link_to 'Back', internships_path %>