config/routes.rb
Rails.application.routes.draw do

  resources :competitions do
    resources :comments, module: :competitions
  end
  resources :volunteers do
    resources :comments, module: :volunteers
  end
  resources :internships do
    resources :comments, module: :internships
  end
  resources :jobs do
    resources :comments, module: :jobs
  end
  devise_for :users

  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/contact'

  authenticated :user do
    root :to => 'welcome#index', as: :authenticated_root
  end
  root :to => 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Student Opportunity Network</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<%= link_to image_tag('SONtitle.png'), root_path, :class =>'navbar-brand' %>
			</div>

			<div id="navbar" class="navbar-collapse collapse">
				<div class="navbar-form navbar-right">
					<div class="form-group" data-no-turbolink>
						<% if current_user %>
							<%= link_to "Sign Out", destroy_user_session_path, method: :delete ,:class =>'btn btn-primary' %>
						<% else %>
							<%= form_for(:user, :url => session_path(:user)) do |f| %>
								<%= f.text_field :email, :autofocus => true, :placeholder => 'Email address',:class =>'form-control'  %>
								<%= f.password_field :password, :placeholder => 'Password',:class =>'form-control' %>
								<%= f.submit 'Sign in' , :class =>'btn btn-primary'%>
								<%= link_to "Sign Up", new_user_registration_path, :class =>'btn btn-primary' %>
							<% end %>
						<% end %>
					</div>
				</div>
			</div><!--/.navbar-collapse -->
		</div>
	</nav>

	<div class="container main_body">

		<% if !current_user %>
			<ul class="nav nav-tabs">
				<li><%= link_to "Home", root_path%></li>
				<li><%= link_to "About Us", welcome_about_path%></li>
				<!--<li><%= link_to "Contact", welcome_contact_path%></li>-->
			</ul>
		<% else %>
			<ul class="nav nav-tabs">
				<li><%= link_to "Jobs", jobs_path%></li>
				<li><%= link_to "Internships", internships_path%></li>
				<li><%= link_to "Competitions", competitions_path%></li>
				<li><%= link_to "Volunteering", volunteers_path%></li>
				<li><%= link_to "My Profile", :action=>"edit", :controller=>"devise/registrations"%></li>
				<li><%= link_to "About Us", welcome_about_path%></li>
				<!--<li><%= link_to "Contact", welcome_contact_path%></li>-->
			</ul>
		<% end %>


		<% if flash[:notice] %>
		<div class="alert alert-success">
			<button type="button" class="close" data-dismiss="alert">&times;
			</button>
			<%= flash[:notice] %>
		</div>
		<% elsif flash[:error] %>
		<div class="alert alert-error">
			<button type="button" class="close" data-dismiss="alert">&times;
			</button>
			<%= flash[:error] %>
		</div>
		<% elsif flash[:alert] %>
		<div class="alert">
			<button type="button" class="close" data-dismiss="alert">&times;
			</button>
			<%= flash[:alert] %>
		</div>
		<% end %>

		<%= yield %>

	</div>

</body>

<footer>
	<p>&copy; Contact us at studentopportunitynetwork@gmail.com for any enquiries you may have.</p>
</footer>

</html>